### ISSUE TITLE
libstdc++ is too old for string_view

### ISSUE THREAD

**Issue by janwilmans** [FredTingaud/quick-bench-back-end#11]
```
#include <string>
#include <string_view>

std::string passthrough_strview(std::string_view str)
{
  return std::string(str);
}
```
![image](https://user-images.githubusercontent.com/5933444/64523484-ac8ca200-d2fc-11e9-8206-167fd7851a93.png)

**Comment by beached** [comment]
The libstdc++ that the gcc 9.x compilers use does have it, along with the libc++.  
But in addition, std::byte is missing because of this too

**Comment by FredTingaud** [comment]
The problem should be solved by the last update.
