### ISSUE TITLE
Clang 15 can't find an appropriate libc++

### ISSUE THREAD

**Issue by cjdb** [FredTingaud/quick-bench-back-end#30]
I get the following when building with `clang++-15 -stdlib=libc++ -std=c++20 -O3`. Choosing Clang 13 and Clang 14 don't have this problem, so I suspect it's just that libc++ 15 isn't installed on the Docker image?

```
./bench: error while loading shared libraries: libc++.so.1: cannot open shared object file: No such file or directory
```

**Comment by FredTingaud** [comment]
I'm unsure which change fixed that and how the system tests didn't catch this at the time, but it seems fixed.
