### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by baileyparker** [FredTingaud/quick-bench-back-end#9]
Any chance you could add a Let's Encrypt cert so that everyone doesn't need to execute JS delivered over HTTP?

**Comment by FredTingaud** [comment]
That is at the top of my todolist.
The website is currently served directly through S3, which would not work with Let's Encrypt, so I need to change the way the site is served first.

**Comment by baileyparker** [comment]
Hmm. Since you've separated the front and backend, it looks like you may be able to just serve the frontend with Github pages by CNAMEing `quick-bench.com` to `github.io` but leaving `back.quick-bench.com` alone. The only downside I can think of is that you'd have to check in compiled assets to a `gh-pages` branch.

**Comment by jamesorlakin** [comment]
I don't know how the backend is hosted (though HTTPS is working there :+1:), but for static frontends on AWS my go-to pattern is to use CloudFront and a free Amazon SSL certificate. The default HTTPS from S3 static hosting can be a bit limiting.

**Comment by FredTingaud** [comment]
Thanks @jamesorlakin , I have found the solution to switch to HTTPS cleanly. I hope to update the website in the coming week.

**Comment by FredTingaud** [comment]
Quick Bench is now served through https.
